org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/ousan/.jdks/corretto-17.0.10
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.builtInKotlin=false
android.newDsl=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
